### ISSUE TITLE
Add a hard cap on maximum accuracy

### ISSUE THREAD

**Issue by LadyAlekto** [Sheep-y/BattleTech_Mods#4]
HI

We found a bug with AIM

Whenever theres too many positive modifiers present it can go into the negative (either giving a NaN% or even start from 0 again)

I would ask, how hard would it be to hardcap it at 100% (or rather 95-99%)

(looking at your quite elegant code i cant find anything but then im an amateur thats happy she made 1 copy paste dll)

**Comment by Sheep-y** [comment]
Very easy to fix.  An oversight on my part.

Good. Now I really have enough bugs on hand to justify fasttracking a bug fix release. @_@

**Comment by Sheep-y** [comment]
Fixed and released.

My code usually described as "highly compressed and normalised", a sign of permanent head damage caused by excessive coding.

So, yeah, it is not easy to read.  Faint on sight and have a short-term memory lost is common after eyes contact, a reflex to protect one's own humanity and sanity from ovis aries. ;)

**Comment by LadyAlekto** [comment]
I got only reports, cannot reproduce it myself, i add the mod json i use
[mod.zip](https://github.com/Sheep-y/BattleTech_Mods/files/2151280/mod.zip)

**Comment by Sheep-y** [comment]
Just want to let you know that razunter should have found the culprit that cause the NaN in issue #6.  I'm looking at it and expect to include it in next udpate.
